### ISSUE TITLE
trident代码问题

### ISSUE THREAD

**Issue by juli8baker** [ian7yang/ASUS-B560m-Plus-WiFi-i7-11700K#2]
博士你好，我是南京林业大学研究网络安全的老师，我看您的论文《[TRIDENT: Towards Detecting and Mitigating Web-based Social Engineering Attacks]》中有给出系统源码，但是按照文中的地址，并没有找到，是不再对外公开了吗？方便的话可以私发我的邮箱（ytduanmu@njfu.edu.cn)吗？万分感谢！！

**Comment by ian7yang** [comment]
代码会在会议开完之后再公开，也需要一点时间整理一下。

**Comment by juli8baker** [comment]
好的，谢谢&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "Ian&nbsp;Yang"; 
Date: 2023年8月3日(星期四) 晚上9:47
To: "ian7yang/ASUS-B560m-Plus-WiFi-i7-11700K"; 
Cc: "端木怡婷"; "Author"; 
Subject: Re: [ian7yang/ASUS-B560m-Plus-WiFi-i7-11700K] trident代码问题 (Issue #2)

&nbsp;


 
代码会在会议开完之后再公开，也需要一点时间整理一下。

**Comment by ian7yang** [comment]
https://github.com/ian7yang/trident is available now.
